"""
Comprehensive catalog of 104 curated topics across 13 diverse categories.
Ensures thorough coverage of all 10 design templates and 12 color themes.
"""
from typing import List, Dict, Any

CATALOG_TOPICS: List[Dict[str, Any]] = [
    # ----------------------------------------------------
    # 1. Technology and AI (8 topics)
    # ----------------------------------------------------
    {
        "id": "tech_001",
        "category": "Technology and AI",
        "topic": "Generative AI Agents in Enterprise Software",
        "design_type": "Infographic",
        "template": "feature_highlights",
        "style": "Cyberpunk Tech",
        "tone": "Visionary",
        "color_theme": "Cyberpunk Tech",
    },
    {
        "id": "tech_002",
        "category": "Technology and AI",
        "topic": "Quantum Computing Milestones & Real-World Horizons",
        "design_type": "Infographic",
        "template": "statistics_showcase",
        "style": "Deep Oceanic",
        "tone": "Analytical",
        "color_theme": "Deep Oceanic",
    },
    {
        "id": "tech_003",
        "category": "Technology and AI",
        "topic": "Edge Computing vs Cloud Architecture",
        "design_type": "Infographic",
        "template": "comparison_layout",
        "style": "Modern Corporate",
        "tone": "Technical",
        "color_theme": "Modern Corporate",
    },
    {
        "id": "tech_004",
        "category": "Technology and AI",
        "topic": "Autonomous AI Agent Architecture Roadmap",
        "design_type": "Infographic",
        "template": "step_by_step_process",
        "style": "Cyberpunk Tech",
        "tone": "Architectural",
        "color_theme": "Cyberpunk Tech",
    },
    {
        "id": "tech_005",
        "category": "Technology and AI",
        "topic": "AI-Powered Automation for Next-Gen Engineering",
        "design_type": "Banner",
        "template": "promotional_banner",
        "style": "Modern Corporate",
        "tone": "Inspiring",
        "color_theme": "Modern Corporate",
    },
    {
        "id": "tech_006",
        "category": "Technology and AI",
        "topic": "Ethical AI Principles for Responsible Innovation",
        "design_type": "Banner",
        "template": "quote_banner",
        "style": "Royal Amethyst",
        "tone": "Reflective",
        "color_theme": "Royal Amethyst",
    },
    {
        "id": "tech_007",
        "category": "Technology and AI",
        "topic": "5 Core Pillars of Modern Machine Learning Pipelines",
        "design_type": "Infographic",
        "template": "list_infographic",
        "style": "Teal Horizon",
        "tone": "Educational",
        "color_theme": "Teal Horizon",
    },
    {
        "id": "tech_008",
        "category": "Technology and AI",
        "topic": "Global AI Adoption Index 2026",
        "design_type": "Infographic",
        "template": "corporate_social",
        "style": "Nordic Minimal",
        "tone": "Executive",
        "color_theme": "Nordic Minimal",
    },

    # ----------------------------------------------------
    # 2. Business and Startups (8 topics)
    # ----------------------------------------------------
    {
        "id": "biz_001",
        "category": "Business and Startups",
        "topic": "Lean Startup Methodology: From MVP to Scale",
        "design_type": "Infographic",
        "template": "step_by_step_process",
        "style": "FinTech Gold",
        "tone": "Practical",
        "color_theme": "FinTech Gold",
    },
    {
        "id": "biz_002",
        "category": "Business and Startups",
        "topic": "SaaS Unit Economics: LTV, CAC & Net Retention",
        "design_type": "Infographic",
        "template": "statistics_showcase",
        "style": "Modern Corporate",
        "tone": "Analytical",
        "color_theme": "Modern Corporate",
    },
    {
        "id": "biz_003",
        "category": "Business and Startups",
        "topic": "Bootstrapping vs Venture Capital Growth Models",
        "design_type": "Infographic",
        "template": "comparison_layout",
        "style": "FinTech Gold",
        "tone": "Objective",
        "color_theme": "FinTech Gold",
    },
    {
        "id": "biz_004",
        "category": "Business and Startups",
        "topic": "Enterprise Founders Accelerator Launch",
        "design_type": "Banner",
        "template": "announcement_banner",
        "style": "Sunset Gradient",
        "tone": "Promotional",
        "color_theme": "Sunset Gradient",
    },
    {
        "id": "biz_005",
        "category": "Business and Startups",
        "topic": "Product-Market Fit Validation Framework",
        "design_type": "Infographic",
        "template": "educational_infographic",
        "style": "Deep Oceanic",
        "tone": "Strategic",
        "color_theme": "Deep Oceanic",
    },
    {
        "id": "biz_006",
        "category": "Business and Startups",
        "topic": "The Mindset of Resilient Venture Leaders",
        "design_type": "Banner",
        "template": "quote_banner",
        "style": "Obsidian Luxe",
        "tone": "Inspiring",
        "color_theme": "Obsidian Luxe",
    },
    {
        "id": "biz_007",
        "category": "Business and Startups",
        "topic": "Essential Features of High-Growth Scaling Orgs",
        "design_type": "Infographic",
        "template": "feature_highlights",
        "style": "Modern Corporate",
        "tone": "Professional",
        "color_theme": "Modern Corporate",
    },
    {
        "id": "biz_008",
        "category": "Business and Startups",
        "topic": "Startup Runway Optimization & Capital Health",
        "design_type": "Infographic",
        "template": "corporate_social",
        "style": "Emerald Growth",
        "tone": "Authoritative",
        "color_theme": "Emerald Growth",
    },

    # ----------------------------------------------------
    # 3. Education (8 topics)
    # ----------------------------------------------------
    {
        "id": "edu_001",
        "category": "Education",
        "topic": "Adaptive Learning Systems & AI Tutors",
        "design_type": "Infographic",
        "template": "educational_infographic",
        "style": "Royal Amethyst",
        "tone": "Insightful",
        "color_theme": "Royal Amethyst",
    },
    {
        "id": "edu_002",
        "category": "Education",
        "topic": "5 Learning Pedagogies for Higher Retention",
        "design_type": "Infographic",
        "template": "list_infographic",
        "style": "Deep Oceanic",
        "tone": "Academic",
        "color_theme": "Deep Oceanic",
    },
    {
        "id": "edu_003",
        "category": "Education",
        "topic": "Continuous Upskilling vs Stagnant Workforces",
        "design_type": "Infographic",
        "template": "comparison_layout",
        "style": "Solar Energy",
        "tone": "Motivational",
        "color_theme": "Solar Energy",
    },
    {
        "id": "edu_004",
        "category": "Education",
        "topic": "Global STEM Literacy Milestones & Metrics",
        "design_type": "Infographic",
        "template": "statistics_showcase",
        "style": "Teal Horizon",
        "tone": "Empirical",
        "color_theme": "Teal Horizon",
    },
    {
        "id": "edu_005",
        "category": "Education",
        "topic": "Next-Gen Interactive Virtual Classrooms",
        "design_type": "Banner",
        "template": "promotional_banner",
        "style": "Royal Amethyst",
        "tone": "Welcoming",
        "color_theme": "Royal Amethyst",
    },
    {
        "id": "edu_006",
        "category": "Education",
        "topic": "Lifelong Curiosity as the Ultimate Competitive Advantage",
        "design_type": "Banner",
        "template": "quote_banner",
        "style": "Nordic Minimal",
        "tone": "Philosophical",
        "color_theme": "Nordic Minimal",
    },
    {
        "id": "edu_007",
        "category": "Education",
        "topic": "The Journey to Technical Mastery",
        "design_type": "Infographic",
        "template": "step_by_step_process",
        "style": "Emerald Growth",
        "tone": "Guiding",
        "color_theme": "Emerald Growth",
    },
    {
        "id": "edu_008",
        "category": "Education",
        "topic": "Modern Digital Learning Platform Architecture",
        "design_type": "Infographic",
        "template": "feature_highlights",
        "style": "Deep Oceanic",
        "tone": "Structured",
        "color_theme": "Deep Oceanic",
    },

    # ----------------------------------------------------
    # 4. Healthcare (8 topics)
    # ----------------------------------------------------
    {
        "id": "health_001",
        "category": "Healthcare",
        "topic": "AI in Medical Diagnostics & Clinical Precision",
        "design_type": "Infographic",
        "template": "feature_highlights",
        "style": "Teal Horizon",
        "tone": "Clinical",
        "color_theme": "Teal Horizon",
    },
    {
        "id": "health_002",
        "category": "Healthcare",
        "topic": "Telemedicine Adoption & Patient Outcomes",
        "design_type": "Infographic",
        "template": "statistics_showcase",
        "style": "Deep Oceanic",
        "tone": "Empirical",
        "color_theme": "Deep Oceanic",
    },
    {
        "id": "health_003",
        "category": "Healthcare",
        "topic": "Preventative Wellness vs Reactive Healthcare",
        "design_type": "Infographic",
        "template": "comparison_layout",
        "style": "Emerald Growth",
        "tone": "Urgent",
        "color_theme": "Emerald Growth",
    },
    {
        "id": "health_004",
        "category": "Healthcare",
        "topic": "Clinical Trial Phases & Patient Safety Protocol",
        "design_type": "Infographic",
        "template": "step_by_step_process",
        "style": "Teal Horizon",
        "tone": "Rigorous",
        "color_theme": "Teal Horizon",
    },
    {
        "id": "health_005",
        "category": "Healthcare",
        "topic": "Comprehensive Digital Health Suite",
        "design_type": "Banner",
        "template": "promotional_banner",
        "style": "Deep Oceanic",
        "tone": "Empathetic",
        "color_theme": "Deep Oceanic",
    },
    {
        "id": "health_006",
        "category": "Healthcare",
        "topic": "Compassion and Precision in Modern Medicine",
        "design_type": "Banner",
        "template": "quote_banner",
        "style": "Teal Horizon",
        "tone": "Inspiring",
        "color_theme": "Teal Horizon",
    },
    {
        "id": "health_007",
        "category": "Healthcare",
        "topic": "5 Habits for Sustainable Mental & Physical Vitality",
        "design_type": "Infographic",
        "template": "list_infographic",
        "style": "Emerald Growth",
        "tone": "Encouraging",
        "color_theme": "Emerald Growth",
    },
    {
        "id": "health_008",
        "category": "Healthcare",
        "topic": "Global Health Resilience & Care Delivery",
        "design_type": "Infographic",
        "template": "corporate_social",
        "style": "Nordic Minimal",
        "tone": "Professional",
        "color_theme": "Nordic Minimal",
    },

    # ----------------------------------------------------
    # 5. Finance (8 topics)
    # ----------------------------------------------------
    {
        "id": "fin_001",
        "category": "Finance",
        "topic": "Algorithmic Wealth Management & Portfolio Allocation",
        "design_type": "Infographic",
        "template": "feature_highlights",
        "style": "FinTech Gold",
        "tone": "Strategic",
        "color_theme": "FinTech Gold",
    },
    {
        "id": "fin_002",
        "category": "Finance",
        "topic": "Decentralized Finance Growth & Security Metrics",
        "design_type": "Infographic",
        "template": "statistics_showcase",
        "style": "FinTech Gold",
        "tone": "Analytical",
        "color_theme": "FinTech Gold",
    },
    {
        "id": "fin_003",
        "category": "Finance",
        "topic": "Compound Investing vs Speculative Trading",
        "design_type": "Infographic",
        "template": "comparison_layout",
        "style": "Obsidian Luxe",
        "tone": "Educational",
        "color_theme": "Obsidian Luxe",
    },
    {
        "id": "fin_004",
        "category": "Finance",
        "topic": "The Roadmap to Long-Term Financial Independence",
        "design_type": "Infographic",
        "template": "step_by_step_process",
        "style": "Emerald Growth",
        "tone": "Empowering",
        "color_theme": "Emerald Growth",
    },
    {
        "id": "fin_005",
        "category": "Finance",
        "topic": "Institutional Treasury & High-Yield Liquidity",
        "design_type": "Banner",
        "template": "promotional_banner",
        "style": "Modern Corporate",
        "tone": "Trustworthy",
        "color_theme": "Modern Corporate",
    },
    {
        "id": "fin_006",
        "category": "Finance",
        "topic": "Risk Management as the Core of Alpha Generation",
        "design_type": "Banner",
        "template": "quote_banner",
        "style": "FinTech Gold",
        "tone": "Prudent",
        "color_theme": "FinTech Gold",
    },
    {
        "id": "fin_007",
        "category": "Finance",
        "topic": "5 Crucial Pillars of Personal Wealth Preservation",
        "design_type": "Infographic",
        "template": "list_infographic",
        "style": "Obsidian Luxe",
        "tone": "Advisory",
        "color_theme": "Obsidian Luxe",
    },
    {
        "id": "fin_008",
        "category": "Finance",
        "topic": "Annual Global Wealth Benchmark Insights",
        "design_type": "Infographic",
        "template": "corporate_social",
        "style": "FinTech Gold",
        "tone": "Executive",
        "color_theme": "FinTech Gold",
    },

    # ----------------------------------------------------
    # 6. Marketing (8 topics)
    # ----------------------------------------------------
    {
        "id": "mkt_001",
        "category": "Marketing",
        "topic": "AI-Driven Omnichannel Marketing Automation",
        "design_type": "Infographic",
        "template": "feature_highlights",
        "style": "Sunset Gradient",
        "tone": "Energetic",
        "color_theme": "Sunset Gradient",
    },
    {
        "id": "mkt_002",
        "category": "Marketing",
        "topic": "Customer Acquisition Cost vs Lifetime Value Benchmark",
        "design_type": "Infographic",
        "template": "statistics_showcase",
        "style": "Sunset Gradient",
        "tone": "Performance-Driven",
        "color_theme": "Sunset Gradient",
    },
    {
        "id": "mkt_003",
        "category": "Marketing",
        "topic": "Organic Growth Strategy vs Paid Performance Ads",
        "design_type": "Infographic",
        "template": "comparison_layout",
        "style": "Solar Energy",
        "tone": "Analytical",
        "color_theme": "Solar Energy",
    },
    {
        "id": "mkt_004",
        "category": "Marketing",
        "topic": "High-Converting Growth Funnel Architecture",
        "design_type": "Infographic",
        "template": "step_by_step_process",
        "style": "Sunset Gradient",
        "tone": "Practical",
        "color_theme": "Sunset Gradient",
    },
    {
        "id": "mkt_005",
        "category": "Marketing",
        "topic": "Transform Brand Engagement with Intelligent Campaigns",
        "design_type": "Banner",
        "template": "promotional_banner",
        "style": "Royal Amethyst",
        "tone": "Compelling",
        "color_theme": "Royal Amethyst",
    },
    {
        "id": "mkt_006",
        "category": "Marketing",
        "topic": "Empathy and Relevance as the True Growth Engine",
        "design_type": "Banner",
        "template": "quote_banner",
        "style": "Sunset Gradient",
        "tone": "Creative",
        "color_theme": "Sunset Gradient",
    },
    {
        "id": "mkt_007",
        "category": "Marketing",
        "topic": "5 Modern Tactics for Content Virality & Resonance",
        "design_type": "Infographic",
        "template": "list_infographic",
        "style": "Solar Energy",
        "tone": "Actionable",
        "color_theme": "Solar Energy",
    },
    {
        "id": "mkt_008",
        "category": "Marketing",
        "topic": "Digital Marketing ROI & Conversion Pulse",
        "design_type": "Infographic",
        "template": "corporate_social",
        "style": "Sunset Gradient",
        "tone": "Dynamic",
        "color_theme": "Sunset Gradient",
    },

    # ----------------------------------------------------
    # 7. Cybersecurity (8 topics)
    # ----------------------------------------------------
    {
        "id": "sec_001",
        "category": "Cybersecurity",
        "topic": "Zero Trust Network Access & Identity Architecture",
        "design_type": "Infographic",
        "template": "feature_highlights",
        "style": "Crimson Shield",
        "tone": "Vigilant",
        "color_theme": "Crimson Shield",
    },
    {
        "id": "sec_002",
        "category": "Cybersecurity",
        "topic": "Global Threat Intelligence & Ransomware Vector Report",
        "design_type": "Infographic",
        "template": "statistics_showcase",
        "style": "Crimson Shield",
        "tone": "Urgent",
        "color_theme": "Crimson Shield",
    },
    {
        "id": "sec_003",
        "category": "Cybersecurity",
        "topic": "Continuous SOC Monitoring vs Periodic Auditing",
        "design_type": "Infographic",
        "template": "comparison_layout",
        "style": "Crimson Shield",
        "tone": "Critical",
        "color_theme": "Crimson Shield",
    },
    {
        "id": "sec_004",
        "category": "Cybersecurity",
        "topic": "Incident Response & Breach Containment Protocol",
        "design_type": "Infographic",
        "template": "step_by_step_process",
        "style": "Cyberpunk Tech",
        "tone": "Disciplined",
        "color_theme": "Cyberpunk Tech",
    },
    {
        "id": "sec_005",
        "category": "Cybersecurity",
        "topic": "Autonomous Endpoint Protection Platform",
        "design_type": "Banner",
        "template": "promotional_banner",
        "style": "Crimson Shield",
        "tone": "Authoritative",
        "color_theme": "Crimson Shield",
    },
    {
        "id": "sec_006",
        "category": "Cybersecurity",
        "topic": "Security is Never a State; It is a Continuous Discipline",
        "design_type": "Banner",
        "template": "quote_banner",
        "style": "Nordic Minimal",
        "tone": "Pragmatic",
        "color_theme": "Nordic Minimal",
    },
    {
        "id": "sec_007",
        "category": "Cybersecurity",
        "topic": "5 Critical Cyber Defense Controls for Cloud Environments",
        "design_type": "Infographic",
        "template": "list_infographic",
        "style": "Crimson Shield",
        "tone": "Technical",
        "color_theme": "Crimson Shield",
    },
    {
        "id": "sec_008",
        "category": "Cybersecurity",
        "topic": "Enterprise Threat Defense & Resilience Index",
        "design_type": "Infographic",
        "template": "corporate_social",
        "style": "Cyberpunk Tech",
        "tone": "Executive",
        "color_theme": "Cyberpunk Tech",
    },

    # ----------------------------------------------------
    # 8. E-commerce (8 topics)
    # ----------------------------------------------------
    {
        "id": "ecom_001",
        "category": "E-commerce",
        "topic": "Headless Commerce Architecture & Instant Checkout",
        "design_type": "Infographic",
        "template": "feature_highlights",
        "style": "Sunset Gradient",
        "tone": "Modern",
        "color_theme": "Sunset Gradient",
    },
    {
        "id": "ecom_002",
        "category": "E-commerce",
        "topic": "Cart Abandonment Reduction & Conversion Rates",
        "design_type": "Infographic",
        "template": "statistics_showcase",
        "style": "Modern Corporate",
        "tone": "Conversion-Focused",
        "color_theme": "Modern Corporate",
    },
    {
        "id": "ecom_003",
        "category": "E-commerce",
        "topic": "Personalized Recommendations vs Generic Catalogues",
        "design_type": "Infographic",
        "template": "comparison_layout",
        "style": "Solar Energy",
        "tone": "Insightful",
        "color_theme": "Solar Energy",
    },
    {
        "id": "ecom_004",
        "category": "E-commerce",
        "topic": "End-to-End Smart Fulfillment & Logistics Pipeline",
        "design_type": "Infographic",
        "template": "step_by_step_process",
        "style": "Teal Horizon",
        "tone": "Operational",
        "color_theme": "Teal Horizon",
    },
    {
        "id": "ecom_005",
        "category": "E-commerce",
        "topic": "Unified Digital Storefront & Multichannel Commerce",
        "design_type": "Banner",
        "template": "promotional_banner",
        "style": "Sunset Gradient",
        "tone": "Vibrant",
        "color_theme": "Sunset Gradient",
    },
    {
        "id": "ecom_006",
        "category": "E-commerce",
        "topic": "The Best Digital Store Feels Tailored for Every Individual",
        "design_type": "Banner",
        "template": "quote_banner",
        "style": "Obsidian Luxe",
        "tone": "Visionary",
        "color_theme": "Obsidian Luxe",
    },
    {
        "id": "ecom_007",
        "category": "E-commerce",
        "topic": "5 Levers to Double Your Online Store Checkout Velocity",
        "design_type": "Infographic",
        "template": "list_infographic",
        "style": "Solar Energy",
        "tone": "Actionable",
        "color_theme": "Solar Energy",
    },
    {
        "id": "ecom_008",
        "category": "E-commerce",
        "topic": "Global Cross-Border E-Commerce Volume Report",
        "design_type": "Infographic",
        "template": "corporate_social",
        "style": "FinTech Gold",
        "tone": "Executive",
        "color_theme": "FinTech Gold",
    },

    # ----------------------------------------------------
    # 9. Real Estate (8 topics)
    # ----------------------------------------------------
    {
        "id": "prop_001",
        "category": "Real Estate",
        "topic": "Smart Building Automation & PropTech Innovation",
        "design_type": "Infographic",
        "template": "feature_highlights",
        "style": "Obsidian Luxe",
        "tone": "Sophisticated",
        "color_theme": "Obsidian Luxe",
    },
    {
        "id": "prop_002",
        "category": "Real Estate",
        "topic": "Commercial Real Estate Yield & Capital Appreciation",
        "design_type": "Infographic",
        "template": "statistics_showcase",
        "style": "FinTech Gold",
        "tone": "Institutional",
        "color_theme": "FinTech Gold",
    },
    {
        "id": "prop_003",
        "category": "Real Estate",
        "topic": "Urban Transit-Oriented Living vs Suburban Sprawl",
        "design_type": "Infographic",
        "template": "comparison_layout",
        "style": "Emerald Growth",
        "tone": "Urban Planning",
        "color_theme": "Emerald Growth",
    },
    {
        "id": "prop_004",
        "category": "Real Estate",
        "topic": "The Real Estate Asset Acquisition Roadmap",
        "design_type": "Infographic",
        "template": "step_by_step_process",
        "style": "Obsidian Luxe",
        "tone": "Structured",
        "color_theme": "Obsidian Luxe",
    },
    {
        "id": "prop_005",
        "category": "Real Estate",
        "topic": "Luxury Architectural Residences Showcase",
        "design_type": "Banner",
        "template": "promotional_banner",
        "style": "Obsidian Luxe",
        "tone": "Elegant",
        "color_theme": "Obsidian Luxe",
    },
    {
        "id": "prop_006",
        "category": "Real Estate",
        "topic": "Architecture is Frozen Music and Living History",
        "design_type": "Banner",
        "template": "quote_banner",
        "style": "Nordic Minimal",
        "tone": "Inspiring",
        "color_theme": "Nordic Minimal",
    },
    {
        "id": "prop_007",
        "category": "Real Estate",
        "topic": "5 High-Value Renovation Upgrades with Highest ROI",
        "design_type": "Infographic",
        "template": "list_infographic",
        "style": "FinTech Gold",
        "tone": "Practical",
        "color_theme": "FinTech Gold",
    },
    {
        "id": "prop_008",
        "category": "Real Estate",
        "topic": "Metro Housing Market Liquidity Trends",
        "design_type": "Infographic",
        "template": "corporate_social",
        "style": "Deep Oceanic",
        "tone": "Market-Savvy",
        "color_theme": "Deep Oceanic",
    },

    # ----------------------------------------------------
    # 10. Productivity (8 topics)
    # ----------------------------------------------------
    {
        "id": "prod_001",
        "category": "Productivity",
        "topic": "Deep Work Systems & Attention Management",
        "design_type": "Infographic",
        "template": "feature_highlights",
        "style": "Nordic Minimal",
        "tone": "Calm & Focused",
        "color_theme": "Nordic Minimal",
    },
    {
        "id": "prod_002",
        "category": "Productivity",
        "topic": "Context Switching Cost & Flow State Metrics",
        "design_type": "Infographic",
        "template": "statistics_showcase",
        "style": "Royal Amethyst",
        "tone": "Data-Backed",
        "color_theme": "Royal Amethyst",
    },
    {
        "id": "prod_003",
        "category": "Productivity",
        "topic": "Async Deep Collaboration vs Fragmented Meetings",
        "design_type": "Infographic",
        "template": "comparison_layout",
        "style": "Modern Corporate",
        "tone": "Pragmatic",
        "color_theme": "Modern Corporate",
    },
    {
        "id": "prod_004",
        "category": "Productivity",
        "topic": "Peak Cognitive Performance Daily Routine",
        "design_type": "Infographic",
        "template": "step_by_step_process",
        "style": "Teal Horizon",
        "tone": "Actionable",
        "color_theme": "Teal Horizon",
    },
    {
        "id": "prod_005",
        "category": "Productivity",
        "topic": "Master Your Workflow with Intelligent Workspace Orchestration",
        "design_type": "Banner",
        "template": "promotional_banner",
        "style": "Nordic Minimal",
        "tone": "Empowering",
        "color_theme": "Nordic Minimal",
    },
    {
        "id": "prod_006",
        "category": "Productivity",
        "topic": "Simplicity is the Prerequisite for True Mastery",
        "design_type": "Banner",
        "template": "quote_banner",
        "style": "Royal Amethyst",
        "tone": "Philosophical",
        "color_theme": "Royal Amethyst",
    },
    {
        "id": "prod_007",
        "category": "Productivity",
        "topic": "5 Habits of Highly Effective Knowledge Workers",
        "design_type": "Infographic",
        "template": "list_infographic",
        "style": "Modern Corporate",
        "tone": "Practical",
        "color_theme": "Modern Corporate",
    },
    {
        "id": "prod_008",
        "category": "Productivity",
        "topic": "Executive Energy Management & Output Metrics",
        "design_type": "Infographic",
        "template": "corporate_social",
        "style": "Solar Energy",
        "tone": "Executive",
        "color_theme": "Solar Energy",
    },

    # ----------------------------------------------------
    # 11. Sustainability (8 topics)
    # ----------------------------------------------------
    {
        "id": "sust_001",
        "category": "Sustainability",
        "topic": "Net Zero Carbon Transition & Clean Grid Infrastructure",
        "design_type": "Infographic",
        "template": "feature_highlights",
        "style": "Emerald Growth",
        "tone": "Inspiring",
        "color_theme": "Emerald Growth",
    },
    {
        "id": "sust_002",
        "category": "Sustainability",
        "topic": "Global Renewable Energy Share & Carbon Abatement",
        "design_type": "Infographic",
        "template": "statistics_showcase",
        "style": "Emerald Growth",
        "tone": "Scientific",
        "color_theme": "Emerald Growth",
    },
    {
        "id": "sust_003",
        "category": "Sustainability",
        "topic": "Circular Economy Lifecycle vs Linear Extractive Model",
        "design_type": "Infographic",
        "template": "comparison_layout",
        "style": "Emerald Growth",
        "tone": "Thought-Provoking",
        "color_theme": "Emerald Growth",
    },
    {
        "id": "sust_004",
        "category": "Sustainability",
        "topic": "Enterprise ESG Decarbonization Roadmap",
        "design_type": "Infographic",
        "template": "step_by_step_process",
        "style": "Teal Horizon",
        "tone": "Action-Oriented",
        "color_theme": "Teal Horizon",
    },
    {
        "id": "sust_005",
        "category": "Sustainability",
        "topic": "Clean Energy Solutions for Sustainable Enterprise",
        "design_type": "Banner",
        "template": "promotional_banner",
        "style": "Emerald Growth",
        "tone": "Forward-Looking",
        "color_theme": "Emerald Growth",
    },
    {
        "id": "sust_006",
        "category": "Sustainability",
        "topic": "We Do Not Inherit the Earth; We Borrow It from Our Children",
        "design_type": "Banner",
        "template": "quote_banner",
        "style": "Emerald Growth",
        "tone": "Profound",
        "color_theme": "Emerald Growth",
    },
    {
        "id": "sust_007",
        "category": "Sustainability",
        "topic": "5 Practical Steps to Reduce Corporate Carbon Footprint",
        "design_type": "Infographic",
        "template": "list_infographic",
        "style": "Teal Horizon",
        "tone": "Constructive",
        "color_theme": "Teal Horizon",
    },
    {
        "id": "sust_008",
        "category": "Sustainability",
        "topic": "Global Environmental Impact & Renewable Milestones",
        "design_type": "Infographic",
        "template": "corporate_social",
        "style": "Emerald Growth",
        "tone": "Impactful",
        "color_theme": "Emerald Growth",
    },

    # ----------------------------------------------------
    # 12. Social Media Awareness (8 topics)
    # ----------------------------------------------------
    {
        "id": "soc_001",
        "category": "Social Media Awareness",
        "topic": "Digital Wellbeing & Mindful Algorithm Consumption",
        "design_type": "Infographic",
        "template": "educational_infographic",
        "style": "Sunset Gradient",
        "tone": "Empathetic",
        "color_theme": "Sunset Gradient",
    },
    {
        "id": "soc_002",
        "category": "Social Media Awareness",
        "topic": "Screen Time Impact & Cognitive Attention Span Studies",
        "design_type": "Infographic",
        "template": "statistics_showcase",
        "style": "Royal Amethyst",
        "tone": "Eye-Opening",
        "color_theme": "Royal Amethyst",
    },
    {
        "id": "soc_003",
        "category": "Social Media Awareness",
        "topic": "Authentic Human Connection vs Algorithmic Validation",
        "design_type": "Infographic",
        "template": "comparison_layout",
        "style": "Sunset Gradient",
        "tone": "Reflective",
        "color_theme": "Sunset Gradient",
    },
    {
        "id": "soc_004",
        "category": "Social Media Awareness",
        "topic": "The 5-Day Digital Detox & Clarity Reset",
        "design_type": "Infographic",
        "template": "step_by_step_process",
        "style": "Nordic Minimal",
        "tone": "Rejuvenating",
        "color_theme": "Nordic Minimal",
    },
    {
        "id": "soc_005",
        "category": "Social Media Awareness",
        "topic": "Cultivating Healthy Online Communities & Constructive Dialogue",
        "design_type": "Banner",
        "template": "promotional_banner",
        "style": "Deep Oceanic",
        "tone": "Unifying",
        "color_theme": "Deep Oceanic",
    },
    {
        "id": "soc_006",
        "category": "Social Media Awareness",
        "topic": "Attention is the Most Precious Currency in Modern Life",
        "design_type": "Banner",
        "template": "quote_banner",
        "style": "Royal Amethyst",
        "tone": "Wisdom",
        "color_theme": "Royal Amethyst",
    },
    {
        "id": "soc_007",
        "category": "Social Media Awareness",
        "topic": "5 Safeguards Against Online Misinformation and Echo Chambers",
        "design_type": "Infographic",
        "template": "list_infographic",
        "style": "Crimson Shield",
        "tone": "Protective",
        "color_theme": "Crimson Shield",
    },
    {
        "id": "soc_008",
        "category": "Social Media Awareness",
        "topic": "Digital Literacy & Community Safety Standards",
        "design_type": "Infographic",
        "template": "corporate_social",
        "style": "Sunset Gradient",
        "tone": "Public Interest",
        "color_theme": "Sunset Gradient",
    },

    # ----------------------------------------------------
    # 13. Corporate Announcements (8 topics)
    # ----------------------------------------------------
    {
        "id": "corp_001",
        "category": "Corporate Announcements",
        "topic": "Strategic Enterprise Merger & Unified Solutions Portfolio",
        "design_type": "Banner",
        "template": "announcement_banner",
        "style": "Modern Corporate",
        "tone": "Momentous",
        "color_theme": "Modern Corporate",
    },
    {
        "id": "corp_002",
        "category": "Corporate Announcements",
        "topic": "Global Innovation Hub Expansion Across Three Continents",
        "design_type": "Infographic",
        "template": "statistics_showcase",
        "style": "Deep Oceanic",
        "tone": "Expansive",
        "color_theme": "Deep Oceanic",
    },
    {
        "id": "corp_003",
        "category": "Corporate Announcements",
        "topic": "Next-Gen AI Core Platform Architecture Launch",
        "design_type": "Banner",
        "template": "announcement_banner",
        "style": "Cyberpunk Tech",
        "tone": "Pioneering",
        "color_theme": "Cyberpunk Tech",
    },
    {
        "id": "corp_004",
        "category": "Corporate Announcements",
        "topic": "Enterprise Cloud Migration Phased Rollout",
        "design_type": "Infographic",
        "template": "step_by_step_process",
        "style": "Modern Corporate",
        "tone": "Systematic",
        "color_theme": "Modern Corporate",
    },
    {
        "id": "corp_005",
        "category": "Corporate Announcements",
        "topic": "Annual Shri Genesis Technology & Innovation Summit",
        "design_type": "Banner",
        "template": "promotional_banner",
        "style": "Royal Amethyst",
        "tone": "Prestigious",
        "color_theme": "Royal Amethyst",
    },
    {
        "id": "corp_006",
        "category": "Corporate Announcements",
        "topic": "Leading Through Innovation, Empathy, and Integrity",
        "design_type": "Banner",
        "template": "quote_banner",
        "style": "Obsidian Luxe",
        "tone": "Executive",
        "color_theme": "Obsidian Luxe",
    },
    {
        "id": "corp_007",
        "category": "Corporate Announcements",
        "topic": "Top 5 Corporate Sustainability Pledges for Net Zero",
        "design_type": "Infographic",
        "template": "list_infographic",
        "style": "Emerald Growth",
        "tone": "Committed",
        "color_theme": "Emerald Growth",
    },
    {
        "id": "corp_008",
        "category": "Corporate Announcements",
        "topic": "Quarterly Financial Record & Market Share Expansion",
        "design_type": "Infographic",
        "template": "corporate_social",
        "style": "FinTech Gold",
        "tone": "Celebratory",
        "color_theme": "FinTech Gold",
    },
]
