"""
SVG Validation & Quality Assurance Engine.
Performs XML syntax validation, viewBox verification, broken reference checking,
text bounds overflow heuristics, WCAG color contrast checks, and AI artifact cleanliness checks.
"""
from __future__ import annotations
import re
import xml.etree.ElementTree as ET
from typing import List, Dict, Set, Optional, Tuple
from engine.models import ValidationResult, ValidationCheck
from engine.palettes import calculate_contrast_ratio, hex_to_rgb


FORBIDDEN_PATTERNS = [
    r"<script",
    r"javascript:",
    r"onload=",
    r"onerror=",
    r"```",
    r"<!ENTITY",
    r"<!DOCTYPE.*SYSTEM",
    r"Here is the SVG",
    r"AI Prompt",
    r"I have generated",
    r"as an AI",
    r"Generated by Assistant",
]


class SVGValidator:
    def __init__(self):
        pass

    def validate(
        self,
        svg_content: str,
        file_path: str = "",
        design_id: str = "",
        category: str = "",
        topic: str = "",
        template: str = "",
    ) -> ValidationResult:
        """
        Executes comprehensive validation suite on SVG content string.
        """
        checks: List[ValidationCheck] = []
        errors: List[str] = []
        warnings: List[str] = []
        score = 100.0

        file_size_kb = round(len(svg_content.encode("utf-8")) / 1024.0, 2)

        # 1. XML Syntax Validation
        root = None
        try:
            root = ET.fromstring(svg_content)
            checks.append(ValidationCheck(name="XML Syntax", passed=True, details="Valid XML document structure."))
        except ET.ParseError as e:
            errors.append(f"XML Parse Error: {str(e)}")
            checks.append(ValidationCheck(name="XML Syntax", passed=False, details=f"Failed to parse XML: {str(e)}"))
            return ValidationResult(
                svg_file=file_path,
                id=design_id,
                category=category,
                topic=topic,
                template=template,
                is_valid=False,
                quality_score=0.0,
                status="failed",
                errors=errors,
                warnings=warnings,
                checks=checks,
                file_size_kb=file_size_kb,
                element_count=0,
            )

        # Count total elements
        element_count = len(list(root.iter()))

        # 2. ViewBox and Dimensions Check
        viewbox = root.attrib.get("viewBox", "")
        width_attr = root.attrib.get("width", "")
        height_attr = root.attrib.get("height", "")

        canvas_width = 1200.0
        canvas_height = 630.0

        if not viewbox:
            errors.append("Missing required viewBox attribute on <svg> root element.")
            checks.append(ValidationCheck(name="ViewBox & Scale", passed=False, details="No viewBox found."))
            score -= 25.0
        else:
            vb_parts = viewbox.strip().split()
            if len(vb_parts) == 4:
                try:
                    canvas_width = float(vb_parts[2])
                    canvas_height = float(vb_parts[3])
                    if canvas_width > 0 and canvas_height > 0:
                        checks.append(ValidationCheck(
                            name="ViewBox & Scale",
                            passed=True,
                            details=f"Valid viewBox: {viewbox} (Aspect ratio {canvas_width:.0f}x{canvas_height:.0f})"
                        ))
                    else:
                        errors.append(f"Invalid non-positive dimensions in viewBox: {viewbox}")
                        score -= 20.0
                except ValueError:
                    errors.append(f"Non-numeric viewBox values: {viewbox}")
                    score -= 20.0
            else:
                errors.append(f"Malformed viewBox attribute: {viewbox}")
                score -= 20.0

        # Check width/height presence
        if not (width_attr and height_attr):
            warnings.append("Missing explicit width/height on <svg> root (viewBox present).")
            score -= 5.0

        # 3. Cleanliness & Security Check
        cleanliness_passed = True
        for pattern in FORBIDDEN_PATTERNS:
            if re.search(pattern, svg_content, re.IGNORECASE):
                errors.append(f"Forbidden or malicious pattern detected: {pattern}")
                cleanliness_passed = False
                score -= 30.0

        # Check for unrendered template tags e.g. {{ title }} or <tspan>{{
        if re.search(r"\{\{.*?\}\}", svg_content):
            warnings.append("Potential unrendered template tags {{...}} detected.")
            cleanliness_passed = False
            score -= 15.0

        checks.append(ValidationCheck(
            name="Clean Code & Security",
            passed=cleanliness_passed,
            details="No tracking scripts, prompt leaks, or template delimiters detected." if cleanliness_passed else "Detected prohibited patterns."
        ))

        # 4. Broken Reference Checking (IDs in url(#...))
        defined_ids: Set[str] = set()
        for elem in root.iter():
            elem_id = elem.attrib.get("id")
            if elem_id:
                defined_ids.add(elem_id)

        used_references = re.findall(r"url\(#([a-zA-Z0-9_\-]+)\)", svg_content)
        broken_refs = [ref for ref in used_references if ref not in defined_ids]
        if broken_refs:
            warnings.append(f"Broken SVG internal references detected: {', '.join(set(broken_refs))}")
            checks.append(ValidationCheck(name="Defs Reference Integrity", passed=False, details=f"Missing IDs: {broken_refs}"))
            score -= 10.0
        else:
            checks.append(ValidationCheck(
                name="Defs Reference Integrity",
                passed=True,
                details=f"All {len(used_references)} url(#id) references resolve correctly in <defs>."
            ))

        # 5. Text Bounds and Overflow Heuristic
        overflow_count = 0
        texts_checked = 0
        for text_elem in root.iter():
            tag = text_elem.tag.split("}")[-1]
            if tag == "text":
                texts_checked += 1
                font_size = float(text_elem.attrib.get("font-size", 16))
                x_val = float(text_elem.attrib.get("x", 0))
                anchor = text_elem.attrib.get("text-anchor", "start")
                
                # Check individual tspans or text directly
                tspans = text_elem.findall("{http://www.w3.org/2000/svg}tspan")
                if not tspans:
                    tspans = text_elem.findall("tspan")
                
                lines_to_check: List[Tuple[str, float]] = []
                if tspans:
                    for ts in tspans:
                        tspan_x = float(ts.attrib.get("x", x_val))
                        lines_to_check.append((ts.text or "", tspan_x))
                else:
                    lines_to_check.append((text_elem.text or "", x_val))

                for line_text, lx in lines_to_check:
                    approx_char_width = font_size * 0.58
                    approx_text_width = len(line_text) * approx_char_width
                    if anchor == "start":
                        end_x = lx + approx_text_width
                    elif anchor == "middle":
                        end_x = lx + (approx_text_width / 2)
                    else:
                        end_x = lx

                    if end_x > canvas_width + 25:
                        overflow_count += 1

        if overflow_count > 0:
            warnings.append(f"Detected {overflow_count} potential text overflow boundaries.")
            checks.append(ValidationCheck(name="Text Layout & Bounds", passed=False, details=f"{overflow_count} text items near canvas border."))
            score -= (overflow_count * 3.0)
        else:
            checks.append(ValidationCheck(
                name="Text Layout & Bounds",
                passed=True,
                details=f"All {texts_checked} text nodes comfortably fit within layout boundaries."
            ))

        # 6. Color Contrast Heuristics
        # Find dominant background hex and primary text hex in SVG
        hex_colors = re.findall(r"#[0-9a-fA-F]{6}", svg_content)
        contrast_ratio: Optional[float] = None
        if len(hex_colors) >= 2:
            # Test contrast between first color (often background) and another bright color
            bg_candidates = [c for c in hex_colors[:3]]
            text_candidates = [c for c in hex_colors if c.upper() in ["#FFFFFF", "#F8FAFC", "#F0FDF4", "#FEF9C3", "#FFF1F2", "#FAF5FF", "#FFF7ED", "#F0FDFA"]]
            if not text_candidates:
                text_candidates = [hex_colors[-1]]
            
            c_ratios = []
            for bg in bg_candidates:
                for tx in text_candidates[:2]:
                    c_ratios.append(calculate_contrast_ratio(bg, tx))
            if c_ratios:
                contrast_ratio = max(c_ratios)
        
        contrast_passed = True
        if contrast_ratio is not None:
            if contrast_ratio < 3.0:
                warnings.append(f"Suboptimal color contrast ratio estimated ({contrast_ratio:.1f}:1).")
                contrast_passed = False
                score -= 8.0
            checks.append(ValidationCheck(
                name="WCAG Color Contrast",
                passed=contrast_passed,
                details=f"Calculated peak contrast ratio: {contrast_ratio:.1f}:1 (Target: >= 4.5:1)."
            ))
        else:
            checks.append(ValidationCheck(
                name="WCAG Color Contrast",
                passed=True,
                details="Gradients and theme colors adhere to pre-validated accessible palettes."
            ))

        # 7. Semantic Hierarchy Check
        has_headline = bool(re.search(r'font-size="[3-5][0-9]"', svg_content))
        has_body = bool(re.search(r'font-size="1[0-8]"', svg_content))
        if has_headline and has_body:
            checks.append(ValidationCheck(
                name="Typography Hierarchy",
                passed=True,
                details="Clear font scale contrast observed between headline and body elements."
            ))
        else:
            warnings.append("Visual hierarchy may lack strong distinction between headlines and body.")
            score -= 5.0
            checks.append(ValidationCheck(
                name="Typography Hierarchy",
                passed=False,
                details="Low variance in font scale sizes."
            ))

        # Final score clamp & status resolution
        score = max(0.0, min(100.0, score))
        if errors:
            status = "failed"
            is_valid = False
        elif warnings:
            status = "warning" if score < 80 else "passed"
            is_valid = True
        else:
            status = "passed"
            is_valid = True

        return ValidationResult(
            svg_file=file_path,
            id=design_id,
            category=category,
            topic=topic,
            template=template,
            is_valid=is_valid,
            quality_score=round(score, 1),
            status=status,
            errors=errors,
            warnings=warnings,
            checks=checks,
            file_size_kb=file_size_kb,
            element_count=element_count,
            contrast_ratio=round(contrast_ratio, 1) if contrast_ratio else None,
        )
